const fs = require('fs');

const code = [
  "'use client'",
  '',
  "import { useState, useEffect } from 'react'",
  "import { QuantumHero } from '@/components/features/hero/QuantumHero'",
  "import { MarqueeBanner } from '@/components/features/hero/MarqueeBanner'",
  "import { QuantumTrain } from '@/components/features/media/QuantumTrain'",
  "import { Loading } from '@/components/common/Loading'",
  '',
  'export default function Home() {',
  '  const [hero, setHero] = useState([])',
  '  const [trending, setTrending] = useState([])',
  '  const [latest, setLatest] = useState([])',
  '  const [topMovies, setTopMovies] = useState([])',
  '  const [topSeries, setTopSeries] = useState([])',
  '  const [loading, setLoading] = useState(true)',
  '',
  '  useEffect(() => {',
  "    fetch('/api/home')",
  '      .then(r => r.json())',
  '      .then(data => {',
  "        const m = (arr, type) => (arr||[]).map(i => ({...i, media_type: type, title_ar: i.title_ar||i.name_ar||'', year: i.year}))",
  "        const tm = m(data.trendingMovies, 'movie')",
  "        const ts = m(data.trendingSeries, 'tv')",
  '        const h = []',
  '        for(let i=0;i<5;i++){if(tm[i])h.push(tm[i]);if(ts[i])h.push(ts[i])}',
  '        setHero(h)',
  '        setTrending([...tm.slice(0,15), ...ts.slice(0,15)])',
  "        setLatest(m(data.latest, 'movie').slice(0,20))",
  "        setTopMovies(m(data.topRated, 'movie').slice(0,15))",
  "        setTopSeries(m(data.series, 'tv').sort((a,b)=>b.vote_average-a.vote_average).slice(0,15))",
  '      })',
  '      .finally(() => setLoading(false))',
  '  }, [])',
  '',
  "  if (loading) return <Loading fullScreen text='جاري التحميل...' />",
  '',
  '  return (',
  '    <div className="min-h-screen bg-gray-950 text-white">',
  '      <div className="page-container">',
  '        <MarqueeBanner />',
  '        <QuantumHero items={hero} />',
  '        <div className="mt-16 space-y-12 pb-16">',
  '          <QuantumTrain items={trending} title="الرائج الآن" icon={<span>🔥</span>} link="/movies" color="cyan" />',
  '          <QuantumTrain items={latest} title="الأحدث" icon={<span>✨</span>} link="/movies" color="green" />',
  '          <QuantumTrain items={topMovies} title="الأعلى تقييماً - أفلام" icon={<span>⭐</span>} link="/movies" color="gold" />',
  '          <QuantumTrain items={topSeries} title="الأعلى تقييماً - مسلسلات" icon={<span>🌟</span>} link="/series" color="purple" />',
  '        </div>',
  '      </div>',
  '    </div>',
  '  )',
  '}'
].join('\n');

fs.writeFileSync('src/app/page.tsx', code, 'utf8');
console.log('DONE - lines:', code.split('\n').length);
console.log('FIRST LINE:', code.split('\n')[0]);
console.log('LAST LINE:', code.split('\n').slice(-1)[0]);
