-- ============================================================
-- SEED GLOBAL KEYWORDS
-- ============================================================
INSERT OR IGNORE INTO global_keywords (keyword_ar, keyword_en, slug) VALUES
('أكشن', 'Action', 'action'),
('إثارة', 'Thriller', 'thriller'),
('مغامرة', 'Adventure', 'adventure'),
('تشويق', 'Suspense', 'suspense'),
('حركة', 'Motion', 'motion-action'),
('مطاردة', 'Chase', 'chase'),
('انفجارات', 'Explosions', 'explosions'),
('قتال', 'Fight', 'fight'),
('دراما', 'Drama', 'drama'),
('رومانسي', 'Romance', 'romance'),
('عاطفي', 'Emotional', 'emotional'),
('حب', 'Love', 'love'),
('خيانة', 'Betrayal', 'betrayal'),
('صداقة', 'Friendship', 'friendship'),
('عائلة', 'Family', 'family'),
('زواج', 'Marriage', 'marriage'),
('طلاق', 'Divorce', 'divorce'),
('جريمة', 'Crime', 'crime'),
('غموض', 'Mystery', 'mystery'),
('تحقيق', 'Investigation', 'investigation'),
('بوليسي', 'Police', 'police'),
('مافيا', 'Mafia', 'mafia'),
('سجن', 'Prison', 'prison'),
('قاتل', 'Killer', 'killer'),
('انتقام', 'Revenge', 'revenge'),
('خيال علمي', 'Sci-Fi', 'sci-fi'),
('فانتازيا', 'Fantasy', 'fantasy'),
('مستقبل', 'Future', 'future'),
('فضاء', 'Space', 'space'),
('روبوت', 'Robot', 'robot'),
('سحر', 'Magic', 'magic'),
('مخلوقات', 'Creatures', 'creatures'),
('رعب', 'Horror', 'horror'),
('مرعب', 'Scary', 'scary'),
('أشباح', 'Ghosts', 'ghosts'),
('ظلام', 'Darkness', 'darkness'),
('تاريخي', 'Historical', 'historical'),
('حرب', 'War', 'war'),
('عصور وسطى', 'Medieval', 'medieval'),
('ثورة', 'Revolution', 'revolution'),
('كوميديا', 'Comedy', 'comedy'),
('مضحك', 'Funny', 'funny'),
('ساخر', 'Satirical', 'satirical'),
('اجتماعي', 'Social', 'social'),
('سياسي', 'Political', 'political'),
('فساد', 'Corruption', 'corruption'),
('فقر', 'Poverty', 'poverty'),
('ثروة', 'Wealth', 'wealth'),
('بطل', 'Hero', 'hero'),
('بطلة', 'Heroine', 'heroine'),
('شرير', 'Villain', 'villain'),
('بطل خارق', 'Superhero', 'superhero'),
('مصري', 'Egyptian', 'egyptian'),
('خليجي', 'Gulf', 'gulf'),
('سعودي', 'Saudi', 'saudi'),
('تركي', 'Turkish', 'turkish'),
('كوري', 'Korean', 'korean'),
('هندي', 'Indian', 'indian'),
('أمريكي', 'American', 'american'),
('بريطاني', 'British', 'british'),
('إسباني', 'Spanish', 'spanish'),
('فرنسي', 'French', 'french'),
('للكبار', 'Adults', 'adults'),
('للعائلة', 'Family Audience', 'family-audience'),
('للأطفال', 'Kids', 'kids-audience'),
('للشباب', 'Youth', 'youth'),
('رمضاني', 'Ramadan', 'ramadan'),
('ديني', 'Religious', 'religious'),
('إسلامي', 'Islamic', 'islamic'),
('أوسكار', 'Oscar', 'oscar'),
('جائزة', 'Award', 'award'),
('مشهور', 'Famous', 'famous'),
('تقنية', 'Technology', 'technology'),
('ذكاء اصطناعي', 'AI', 'artificial-intelligence'),
('إنترنت', 'Internet', 'internet'),
('رياضة', 'Sports', 'sports'),
('كرة قدم', 'Football', 'football'),
('ملاكمة', 'Boxing', 'boxing');
