-- ============================================================
-- SEED GENRES
-- ============================================================
INSERT OR IGNORE INTO genres (tmdb_id, name_ar, name_en, slug, applies_to) VALUES
(28,    'أكشن',             'Action',             'action',          'all'),
(12,    'مغامرة',           'Adventure',          'adventure',       'all'),
(16,    'رسوم متحركة',      'Animation',          'animation',       'all'),
(35,    'كوميديا',          'Comedy',             'comedy',          'all'),
(80,    'جريمة',            'Crime',              'crime',           'all'),
(99,    'وثائقي',           'Documentary',        'documentary',     'all'),
(18,    'دراما',            'Drama',              'drama',           'all'),
(10751, 'عائلي',            'Family',             'family',          'all'),
(14,    'خيال',             'Fantasy',            'fantasy',         'all'),
(36,    'تاريخي',           'History',            'history',         'all'),
(27,    'رعب',              'Horror',             'horror',          'all'),
(10402, 'موسيقى',           'Music',              'music',           'all'),
(9648,  'غموض',             'Mystery',            'mystery',         'all'),
(10749, 'رومانسي',          'Romance',            'romance',         'all'),
(878,   'خيال علمي',        'Sci-Fi',             'sci-fi',          'all'),
(53,    'إثارة',            'Thriller',           'thriller',        'all'),
(10752, 'حرب',              'War',                'war',             'all'),
(37,    'غرب أمريكي',       'Western',            'western',         'movie'),
(10759, 'أكشن ومغامرة',     'Action & Adventure', 'action-adventure','series'),
(10762, 'أطفال',            'Kids',               'kids',            'series'),
(10763, 'أخبار',            'News',               'news',            'series'),
(10764, 'ريالتي',           'Reality',            'reality',         'series'),
(10765, 'خيال علمي وخارق',  'Sci-Fi & Fantasy',   'sci-fi-fantasy',  'series'),
(10766, 'مسلسل درامي',      'Soap',               'soap',            'series'),
(10768, 'حرب وسياسة',       'War & Politics',     'war-politics',    'series'),
(NULL,  'أنيمي',            'Anime',              'anime',           'anime'),
(NULL,  'مصري',             'Egyptian',           'egyptian',        'all'),
(NULL,  'خليجي',            'Gulf',               'gulf',            'all'),
(NULL,  'سعودي',            'Saudi',              'saudi',           'all'),
(NULL,  'تركي',             'Turkish',            'turkish',         'all'),
(NULL,  'كوري',             'Korean',             'korean',          'all'),
(NULL,  'هندي',             'Indian',             'indian',          'all'),
(NULL,  'إسباني',           'Spanish',            'spanish',         'all'),
(NULL,  'فرنسي',            'French',             'french',          'all'),
(NULL,  'ديني',             'Religious',          'religious',       'all'),
(NULL,  'رياضي',            'Sports',             'sports',          'all'),
(NULL,  'سياسي',            'Political',          'political',       'all'),
(NULL,  'اجتماعي',          'Social',             'social',          'all');